services:
  bdd:
    image: mariadb:12.2.2
    container_name: my_bachelor_motors_bdd
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: motdepasse
      MARIADB_DATABASE: my_bachelor_motors

    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: