spring:
  application:
    name: my_bachelor_motors
  datasource:
    #url: jdbc:mariadb://localhost:3307/my_bachelor_motors
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:8080}
app:
  secret-key: ${DB_SECRET_KEY}
  expiration-time: ${DB_EXPIRATION_TIME}