spring:
  application:
    name: my_bachelor_motors
  datasource:
    #url: jdbc:mariadb://localhost:3307/my_bachelor_motors
    url: ${DB_URL:jdbc:mariadb://mysql-damtab.alwaysdata.net/damtab_mmotors}
    username: ${DB_USERNAME:damtab_mmotors}
    password: ${DB_PASSWORD:DamienM_Motors1BDD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:8080}
app:
  secret-key: ${DB_SECRET_KEY:07f612faa8eaadc715811e244a9d84fdd17eb4e2b1801983d173ee41e06caab4}
  expiration-time: ${DB_EXPIRATION_TIME:900000}